apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8300"
    port: 8300
    targetPort: 8300
  selector:
    service: backend-user
