version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: andrewjameswormald/udagram:reverseproxy-latest
  backend_user:
    build:
      context: ../../backend-user
    image: andrewjameswormald/udagram:user-latest
  backend_feed:
    build:
      context: ../../backend-feed
    image: andrewjameswormald/udagram:feed-latest
  frontend:
    build:
      context: ../../frontend
    image: andrewjameswormald/udagram:frontend-latest
